	
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Abigail Helena do Nascimento Severiano', '','Gerência de Comunicação Social',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Ademar Braz Winter', '','Gabinete Vereador Ademar Braz Winter',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Adriane Schimainski dos Santos', '','Gabinete da Presidência (Exercício 2017)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Alais Olska', '','Gabinete Vereador Ademar Braz Winter',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Alamir Mengarda', '','Gabinete Vereador Anderson Kassner',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Aline Vicente Bories', '','Gabinete Vereador Arlindo Rincos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Almir Giese', '','Gabinete Vereador Ronaldo José de Souza',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Ana Paula Ern', '','Gerência de Atos Legislativos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Anderson Kassner', '','Gabinete Vereador Anderson Kassner',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Andreas Kulczynskyj', '','Gerência de Comunicação Social',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Anesio Luiz Alexandre', '','Gabinete Vereador Isair Moser',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Ariane Cristine Correa', '','PROCURADORIA GERAL LEGISLATIVA',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Arlindo Rincos', '','Gabinete Vereador Arlindo Rincos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Bruna Piccoli', 'Direito','Gerência de Atos Legislativos',	150	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Carlos Ricardo Woeltje', '','DIRETORIA DE CONTABILIDADE E FINANÇAS',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Caroline Dal Santo', 'Comunicação Social - Publicidade e Propaganda','Gerência de Comunicação Social',	150	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Celestino Klinkoski', '','Gabinete Vereador Celestino Klinkoski',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Cristian da Paz Braga', 'Ensino Médio','Gerência de Comunicação Social',	100	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Daniele de Souza', '','Gabinete Vereador Jaime Negherbon(suplente)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Debora Lanznaster Vegini', '','Gerência de Administração e Serviços',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Dinalberto De Lucca Moreira', '','Gabinete Vereador Jaime Negherbon(suplente)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Edenilson Jose Pasquetti', '','Gabinete Vereador Marcelindo Carlos Gruner',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Eliezer Antunes', '','Chefia de Patrimônio e Serviços',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Elisabete Bertoli', '','Gabinete Vereador Anderson Kassner',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Eugenio Jose Juraszek', '','Gabinete Vereador Eugenio José Juraszek',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Fabiana de Souza Stringari', '','Chefia de Administração',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Fernanda Fanton', 'Comunicação Social - Publicidade e Propaganda','Gerência de Comunicação Social',	150	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Francielle Belarmino Boeing', '','Gerência de Atos Legislativos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Francisca Emilia Saraiva Terto', '','Gabinete Vereador Ademar Braz Winter',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Idianara dos Santos', '','Chefia de Patrimônio e Serviços',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Irineu Pasold', '','Gabinete Vereador Irineu Pasold(suplente)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Isabel da Silva', '','Gabinete Vereador Marcelindo Carlos Gruner',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Isair Moser', '','Gabinete Vereador Isair Moser',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Jackson Jose de Avila', '','Gabinete Vereador Jackson José de Ávila(suplente)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Jaime Negherbon', '','Gabinete Vereador Jaime Negherbon(suplente)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Joao Modesto da Silveira', '','APOSENTADORIA OU PENSÕES',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Joel Luis Correa', '','Gerência de Comunicação Social',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Josue Kasmirski', '','Gerência de Atos Legislativos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Larissa Mendes Soares', '','Chefia de Administração',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Laudir Dalpiaz', '','Gabinete Vereador Eugenio José Juraszek',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Marcelindo Carlos Gruner', '','Gabinete Vereador Marcelindo Carlos Gruner',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Maria do Carmo Delgado de Souza', '','DIRETORIA DE ADMINISTRAÇÃO GERAL',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Mariana Schmitz Martins', '','Chefia de Patrimônio e Serviços',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Mariana Sciascia Riedel Fischer', '','Chefia de Patrimônio e Serviços',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Mateus Cidral Machado', '','Gerência de Comunicação Social',	150	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Mauricio Silva Rodolpho', '','Chefia de Administração',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Naiana Sousa Pereira', '','DIRETORIA DE CONTABILIDADE E FINANÇAS',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Neri de Souza', '','Gabinete Vereador Celestino Klinkoski',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Patrick Titz', '','Gabinete Vereador Pedro Anacleto Garcia',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Pedro Anacleto Garcia', '','GABIENTE DA PRESIDÊNCIA 2017-2020',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Pietro Di Carlo Manfrini Galvan', '','Gerência de Atos Legislativos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Polyana Carolina de Souza', '','Chefia de Patrimônio e Serviços',	150	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Polyana Gabriella Martim', 'Ensino Medio','Chefia de Administração',	100	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Regis Wojahn Junior', '','Chefia de Administração',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Rogerio Nivaldo Winter', '','DIRETORIA DE CONTABILIDADE E FINANÇAS',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Ronaldo Jose de Souza', '','Gabinete Vereador Ronaldo José de Souza',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Ronaldo Wolski', '','Gabinete Vereador Eugenio José Juraszek',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Rudimar Bruch', '','Gabinete Vereador Ronaldo José de Souza',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Sandra M Rodrigues Batistella Kaspchak', '','Gerência de Comunicação Social',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Sergio Zapella', '','Gabinete Vereador Celestino Klinkoski',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Simone Jark', '','Chefia de Patrimônio e Serviços',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Sonara Joner Cardozo', '','Gabinete Vereador Jackson José de Ávila(suplente)',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Sueli Maria Schiochet', '','Gabinete Vereador Pedro Anacleto Garcia',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Tarcizio Rodrigues Pinto', '','Chefia de Administração',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Tiago Rosario de Santana', '','Gerência de Comunicação Social',	150	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Valmor Zonta Filho', '','Gabinete Vereador Isair Moser',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Venicio Goldacker', '','Gabinete Vereador Arlindo Rincos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Vitoria Toledo de Aragao', '','PROCURADORIA GERAL LEGISLATIVA',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Viviane Liebl Rocha', '','Gerência de Atos Legislativos',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Wagner Leandro Lopes', '','Gerência de Comunicação Social',	200	,	1	)
	INSERT INTO PESSOAS (Nome, Curso, Cargo, Horas, UnidadeId) values('Wilson Pinter', '','Gabinete Vereador Jackson José de Ávila(suplente)',	200	,	1	)
											
